# Generated by Django 3.1.3 on 2021-10-19 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_board_modefy_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='modefy_date',
            new_name='modify_date',
        ),
    ]
